export const AVAILABLE_COLORS = [
  'білий',
  'чорний',
  'сірий',
  'синій',
  'блакитний',
  'зелений',
  'жовтий',
  'червоний',
  'коричневий',
  'бежевий',
  'рожевий',
  'мʼятний',
  'пастельні відтінки',
];

// export const AVAILABLE_COLORS = [
//   'white',
//   'black',
//   'gray',
//   'blue',
//   'light_blue',
//   'green',
//   'yellow',
//   'red',
//   'brown',
//   'beige',
//   'pink',
//   'mint',
//   'pastel_shades',
// ];
